config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers, only: [:index, :create]
  end

  resources :answers, only: [:update]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, presence: true, length: { minimum: 50 }
  validates :question, presence: true

  def markdown
    
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answers = @question.answers.order(best: :desc, created_at: :asc)
    @best_answer = @answers.where(best: true).first

    if @answer.save
      flash[:notice] = "Answer saved successfully"
      redirect_to question_path(@question)
    else
      flash.now[:error] = "Answer must be at least 50 characters"
      render "questions/show"
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    @all_answers = @question.answers
    @all_answers.update_all(best: false)
    @answer.update_attributes(best: true)


    redirect_to question_path(@answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(best: :desc, created_at: :asc)
    @best_answer = @answers.where(best: true).first
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = "Question created!"
      redirect_to @question
    else
      flash.now[:error] = @question.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(question_params)

    if @question.save
      redirect_to @question
    else
      flash[:error] = @question.errors.full_messages.join(", ")
      redirect_to edit_question_path(@question)
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    flash[:notice] = "Question successfully deleted!"
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Megrim' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Copious Questions</li>
          <li>
            <a href="#">Options</a>
            <ul class="menu vertical">
              <li><a href="#">Login</a></li>
              <li><a href="#">Logout</a></li>
            </ul>
          </li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search"></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div>
    <div class="container">
      <div class="row top-margin">
        <div class="column">


          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/questions/_flash.html.erb
<div class="flash">
  <% flash.each do |name, msg| -%>
     <%= content_tag :div, msg, class: name %>
   <% end -%>
 </div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <div class="row">
    <div class="medium-6 medium-centered columns">
      <div class="input-group">
        <span class="input-group-label"><%= f.label :title %></span>
          <%= f.text_field :title, class: "input-group-field" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="medium-6 medium-centered columns">
      <div class="input-group big-description">
        <span class="input-group-label"><%= f.label :description %></span>
          <%= f.text_area :description, class: "input-group-field big-description"%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="medium-6 medium-centered columns">
      <div class="action">
        <%= f.submit "Submit", class: :button %>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'flash' %>

<%= render 'form' %>

<%= link_to "Delete Question", question_path(@question), method: :delete, class: :button %>

<%= link_to 'Back', question_path, class: :button %>

app/views/questions/index.html.erb
<p class="page-header">Questions</p>
<%= render 'flash' %>

  <ul class="no-margin">
    <% @questions.each do |question| %>
      <li><%= link_to markdown(question.title), question_path(question) %></li>
    <% end %>
  </ul>
<br>


<%= button_to "Add Question", new_question_path, method: :get, class: :button %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'flash' %>

<%= render 'form' %>

<%= link_to 'Back', questions_path, class: :button %>

app/views/questions/show.html.erb
<h3>Question:</h3>
<p><%= markdown(@question.title) %></p>
<h3>Description:</h3>
<p>
  <%= markdown(@question.description) %>
</p>

<%= button_to "Edit Question", edit_question_path(@question), method: :get, class: "button" %>
<%= button_to "Delete Question", @question, method: :delete, class: "button" %>

<br>

<%= render 'questions/flash' %>

<br>

<h3>Add Answer</h3>

<%= form_for [@question, @answer] do |f| %>
  <div class="row">
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit Answer', class: :button %>
  </div>
<% end %>

<br>

<h4>Answers:</h4>
<% unless @question.answers.nil? %>
    <div>
      <ul class="answers">
        <% @answers.each do |answer| %>
          <% if answer == @best_answer %>
            <div class="best_answer">
              <li id="answer-callout">Best Answer!</li>
              <li><%= markdown(answer.description) %></li>
            </div>
            <% else %>
            <li><%= markdown(answer.description) %><%= button_to 'Best Answer!', answer, method: :patch, class: "button best-answer" %></li>
            <% end %>
          <% end %>
      </ul>
    </div>
    <% end %>
    <br>


<%= link_to 'Back', questions_path, class: :button %>